GET http://{{rp2host}}:{{rp2httpport}}/index.html

#####
GET http://{{rp2host}}:{{rp2httpport}}/main.html

#####
GET http://{{rp2host}}:{{rp2httpport}}/api/dfsf

#####
GET http://{{rp2host}}:{{rp2httpport}}/api/settings

#####
GET http://{{rp2host}}:{{rp2httpport}}/api/input_pin_value